[package]
name=causerie
version=1.0

[requires]
packages=LazUtils

[compiler]
unitdir=./src/base:./src/parse
targetdir=./build
unittargetdir=./lib
includedir=./src/base:./src/parse

[target]
programs=causerie
units=classwork parsing
